name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Windows Executable
    runs-on: ubuntu-latest # Use Ubuntu as the build host

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24 # Specify your Go version

      # Step 3: Build the Windows executable
      - name: Build for Windows
        run: |
          # Set environment variables for Windows build
          env GOOS=windows GOARCH=amd64 go build -o output/app.exe

      # Step 4: Upload artifact (Fixing `upload-artifact` issue)
      - name: Upload built Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: output/app.exe