name: Build and Deploy Go Application for Linux and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build Go Application for Linux
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2' # Use Go version 1.24.2

      # Step 3: Cache Go modules and build artifacts
      - name: Cache Go modules and builds
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            $HOME/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Run tests before building
      - name: Run Go Tests
        run: go test ./...

      # Step 5: Build the application for Linux
      - name: Compile Go Binary for Linux
        shell: bash
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/seuic_reader main.go
          ls -lh build/

      # Step 6: Upload the artifact
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: seuic_reader-linux-amd64
          path: build/

  build-windows:
    name: Build Go Application for Windows
    runs-on: ubuntu-latest
    needs: [build-linux] # Ensure Linux build runs before this

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      # Step 3: Build the Windows executable
      - name: Compile Go Binary for Windows
        run: |
          mkdir -p output
          GOOS=windows GOARCH=amd64 go build -o output/app.exe
          ls -lh output/

      # Step 4: Upload the artifact
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: output/app.exe

  deploy:
    name: Deploy Go Application
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows] # Ensure both builds are complete before deploying

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download Linux artifact
      - name: Download Linux Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: seuic_reader-linux-amd64
          path: deploy/linux/

      # Step 3: Download Windows artifact
      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: deploy/windows/

      # Step 4: Deploy (placeholder for your deployment logic)
      - name: Deploy to Remote Server
        run: |
          echo "Deploying Go Application builds for Linux and Windows..."
          echo "Linux build deployed from deploy/linux/"
          echo "Windows build deployed from deploy/windows/"